### ISSUE TITLE
Volume mount erase_on_boot flag interprets non-empty strings as true by default

### ISSUE THREAD

**Issue by geekity** [zalando-stups/taupage#318]
When deploying a stack backed by ebs volume using senza, the senza.yaml config interprets a non-empty string in `erase_on_boot` flag as true. For instance the following config 

```
mounts:
   /data:
      partition: /dev/xvdk
      filesystem: ext4
      erase_on_boot: "false"
      options: noatime,nodiratime,nobarrier
```

has resulted in our persisted data being wiped on every reboot. It would be great if there could be some check for this since it is very easy to miss and hard to troubleshoot.
