### ISSUE TITLE
Add custom SenzaInfo fields to the Scalyr Agent

### ISSUE THREAD

**Issue by tgrigoryan** [zalando-stups/taupage#385]
It would be nice to include custom fields specified under the `SenzaInfo` section in logs as a field/column.

**The use case** 
We have separate `senza.yaml` files with the same `SenzaInfo.StackName` per each environment (integration, staging and etc) and we are using `SenzaInfo.Environment` field to specify the environment of the stack. 
Since we get all our logs from all environments in the single place in Scalyr, it would be nice to be able to filter them by `Environment` field.

```yaml
SenzaInfo:
  StackName: our-app-name
  Environment: integration
```
